/**
 * `bun run docs:cli` —— 用路由表元数据生成 `docs/cli.md` 的命令参考段。
 *
 * 生成段夹在两行标记之间，标记之外的手写内容原样保留：文档里"为什么这么设计"的部分
 * 只有人能写，"有哪些参数、值域是什么"只有代码知道。让后者自动生成，是因为手写的那份
 * 一定会漂移——而漂移的参数文档比没有文档更糟：读者照着敲，命令报错。
 *
 * 漂移由 `src/cli/docs.test.ts` 守：生成结果与磁盘内容不一致时门禁失败。
 */

import { readFileSync, writeFileSync } from "node:fs";

import { cliSchema, type CliSchema } from "../src/cli/parse";

export const BEGIN = "<!-- BEGIN: generated by `bun run docs:cli` — 勿手改 -->";
export const END = "<!-- END: generated -->";

/** 版本号只影响生成段的一行标注，读不到就退化为 0.0.0（与 schema 命令同款）. */
function version(): string {
  try {
    const pkg = JSON.parse(
      readFileSync(new URL("../package.json", import.meta.url), "utf8"),
    ) as { version?: string };
    return pkg.version ?? "0.0.0";
  } catch {
    return "0.0.0";
  }
}

function flagRow(f: CliSchema["globals"][number]): string {
  const domain =
    f.values !== undefined
      ? f.values.join(" \\| ")
      : f.format !== undefined
        ? f.format
        : f.type === "boolean"
          ? "开关"
          : "字符串";
  return `| \`--${f.name}\` | ${domain} | ${f.required === true ? "是" : "否"} | ${f.default ?? "—"} | ${f.desc}${f.example === undefined ? "" : `（例：\`${f.example}\`）`} |`;
}

/** 路由表 → markdown（纯函数：生成器与漂移测试共用同一份输出）. */
export function renderCliDocs(schema: CliSchema): string {
  const out: string[] = [
    BEGIN,
    "",
    `> 本段由 \`bun run docs:cli\` 从 \`src/cli/parse.ts\` 的路由表生成（CLI v${schema.version}）。`,
    "> 机器可读的同一份数据：`vagent schema --json`。",
    "",
    "### 全局参数",
    "",
    "| 参数 | 值域 | 必填 | 默认 | 说明 |",
    "| --- | --- | --- | --- | --- |",
    ...schema.globals.map(flagRow),
    "",
    "### 退出码",
    "",
    "| 码 | 含义 |",
    "| --- | --- |",
    ...schema.exitCodes.map((e) => `| ${e.code} | ${e.meaning} |`),
  ];

  for (const group of schema.groups) {
    const commands = schema.commands.filter((c) => c.group === group.id);
    if (commands.length === 0) continue;
    out.push("", `### ${group.title}`);
    for (const c of commands) {
      out.push("", `#### \`${c.route}\``, "", "```", c.usage, "```", "");
      out.push(
        `${c.summary}（代价：${c.cost === "expensive" ? "贵，先 --dry-run" : "轻"}）`,
      );
      if (c.requires.length > 0) {
        out.push(
          "",
          `**前置**：${c.requires.map((r) => `\`${r}\``).join(" → ")}`,
        );
      }
      if (c.positionals.length > 0) {
        out.push("", "| 位置参数 | 说明 |", "| --- | --- |");
        for (const p of c.positionals) {
          out.push(
            `| \`<${p.name}>\` | ${p.desc}${p.example === undefined ? "" : `（例：\`${p.example}\`）`} |`,
          );
        }
      }
      if (c.flags.length > 0) {
        out.push(
          "",
          "| 参数 | 值域 | 必填 | 默认 | 说明 |",
          "| --- | --- | --- | --- | --- |",
          ...c.flags.map(flagRow),
        );
      }
      if (c.produces.length > 0) {
        // 列表前必须空一行：prettier 会自己补，补出来的文件就和生成结果不一致了
        out.push("", "**产物**：", "");
        for (const w of c.produces) out.push(`- \`${w}\``);
      }
      if (c.stopHint !== undefined) out.push("", `⏸ ${c.stopHint}`);
      for (const note of c.notes) out.push("", `- ${note}`);
    }
  }

  out.push("", END, "");
  return out.join("\n");
}

/**
 * 比较用的规范化：prettier 会把 markdown 表格补齐成等宽列，而生成器输出的是紧凑写法。
 * 漂移门禁关心的是**内容**是否一致，不是列宽——所以两边都折叠成单空格再比。
 */
export function normalizeMd(text: string): string {
  return text
    .split("\n")
    .map((line) => {
      const one = line.replace(/\s+/g, " ").trimEnd();
      // 分隔行的破折号数量也是 prettier 的排版结果，一律折叠成 ---
      return /^\|[\s|:-]+\|$/.test(one)
        ? one.replace(/-{2,}/g, "---").replace(/\s+/g, " ")
        : one;
    })
    .join("\n")
    .trim();
}

/** 把生成段写回文档的标记块内（标记必须已存在）. */
export function spliceGenerated(doc: string, generated: string): string {
  const start = doc.indexOf(BEGIN);
  const end = doc.indexOf(END);
  if (start === -1 || end === -1) {
    throw new Error(
      `docs/cli.md 缺少生成标记；请保留这两行：\n${BEGIN}\n${END}`,
    );
  }
  return (
    doc.slice(0, start) + generated.trimEnd() + doc.slice(end + END.length)
  );
}

if (import.meta.main) {
  const docPath = new URL("../docs/cli.md", import.meta.url);
  const doc = readFileSync(docPath, "utf8");
  writeFileSync(
    docPath,
    spliceGenerated(doc, renderCliDocs(cliSchema(version()))),
  );
  console.log(
    `✅ 已更新 docs/cli.md 的命令参考段（${cliSchema(version()).commands.length} 条命令）`,
  );
}
